name: CI

on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check out git tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn run build:ci

      - name: Get commit ID from git describe
        run: echo "git_describe=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Create extension ZIP
        uses: actions/upload-artifact@v3
        with:
          name: timing71-chrome-plugin-${{env.git_describe}}
          path: |
            build/*
            !build/*.js.map

      - name: Create JS sourcemaps
        uses: actions/upload-artifact@v3
        with:
          name: timing71-chrome-plugin-${{env.git_describe}}-sourcemaps
          path: build/*.js.map
